// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RePOS.Data;

#nullable disable

namespace RePOS.Migrations
{
    [DbContext(typeof(RePosDBContext))]
    [Migration("20250505203500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RePOS.Models.TbCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("RePOS.Models.TbItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Category")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("TbCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TbCategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("RePOS.Models.TbOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PaymentMethod")
                        .HasColumnType("bigint");

                    b.Property<long?>("TbPaymentMethodId")
                        .HasColumnType("bigint");

                    b.Property<long>("Total")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TbPaymentMethodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RePOS.Models.TbOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("Qty")
                        .HasColumnType("bigint");

                    b.Property<long?>("TbItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TbOrderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TbItemId");

                    b.HasIndex("TbOrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RePOS.Models.TbPaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("RePOS.Models.TbPermissions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("RePOS.Models.TbRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Permissions")
                        .HasColumnType("bigint");

                    b.Property<long?>("TbPermissionsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TbPermissionsId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RePOS.Models.TbStaff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Role")
                        .HasColumnType("bigint");

                    b.Property<long?>("TbRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TbRoleId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("RePOS.Models.TbItem", b =>
                {
                    b.HasOne("RePOS.Models.TbCategory", "TbCategory")
                        .WithMany("Items")
                        .HasForeignKey("TbCategoryId");

                    b.Navigation("TbCategory");
                });

            modelBuilder.Entity("RePOS.Models.TbOrder", b =>
                {
                    b.HasOne("RePOS.Models.TbPaymentMethod", "TbPaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("TbPaymentMethodId");

                    b.Navigation("TbPaymentMethod");
                });

            modelBuilder.Entity("RePOS.Models.TbOrderItem", b =>
                {
                    b.HasOne("RePOS.Models.TbItem", "TbItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("TbItemId");

                    b.HasOne("RePOS.Models.TbOrder", "TbOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("TbOrderId");

                    b.Navigation("TbItem");

                    b.Navigation("TbOrder");
                });

            modelBuilder.Entity("RePOS.Models.TbRole", b =>
                {
                    b.HasOne("RePOS.Models.TbPermissions", "TbPermissions")
                        .WithMany("Roles")
                        .HasForeignKey("TbPermissionsId");

                    b.Navigation("TbPermissions");
                });

            modelBuilder.Entity("RePOS.Models.TbStaff", b =>
                {
                    b.HasOne("RePOS.Models.TbRole", "TbRole")
                        .WithMany("Staffs")
                        .HasForeignKey("TbRoleId");

                    b.Navigation("TbRole");
                });

            modelBuilder.Entity("RePOS.Models.TbCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RePOS.Models.TbItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RePOS.Models.TbOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RePOS.Models.TbPaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RePOS.Models.TbPermissions", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("RePOS.Models.TbRole", b =>
                {
                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
